### PR TITLE
Rework of the API with witnesses

### PR DESCRIPTION
**Pull request by Drup**
With this, the API is more applicative. There is still no proper `map` function though.
The API would be even better if we had `Re.witness` of type `Re.t -> string`. That would allow us to remove the string argument for `Tyre.regex`.

### CODE REVIEW

**Comment by Drup** [comment]
cc @rgrinberg

**Comment by rgrinberg** [comment]
Looks good. Did you forget to change the `*>` and `<*` forms?

**Comment by Drup** [comment]
Should I change them ? They do correspond to the usual applicative operators now.

**Comment by rgrinberg** [comment]
Then let's leave them.

Although I haven't checked they fellow the applicative laws yet :)

**Comment by rgrinberg** [comment]
Could you document the string parameter in the new regex function?

**Comment by Drup** [comment]
@rgrinberg No need, I just removed it. ;)

I tried to change `*>` to `&>`, and it's actually not a great idea, it makes things less convenient (and need more parens).

**Comment by Drup** [comment]
I added your ini example in the repository, it's a nice example to judge the improvements. :)

**Comment by Drup** [comment]
I'm wondering if `stamp` is worth including, and if yes, under which name.

**Comment by rgrinberg** [comment]
Do you have an example of where stamp would be used? Don't quite see the utility myself.

**Comment by Drup** [comment]
It's used for printing ignored elements. For example, if you were to do `pos_int <* bool` and you ask to `eval re 3`, the printed bool is out of your control. `stamp` allows you to change the default value : `pos_int <* stamp false bool`.

You are right, it's probably not very useful ....

**Pull request merged**
