### PR TITLE
Updates jbuild files to dune files

### PR DESCRIPTION
**Pull request by anuragsoni**
Signed-off-by: Anurag Soni <anurag@sonianurag.com>

### CODE REVIEW

**Comment by Drup** [comment]
Huh, look like the `[@specialize]` annotation on `and` is a syntax error under 4.02. I actually don't really care about 4.02, so we can just drop it. Can you remove it from the travis file and change the opam constraint ?

**Comment by anuragsoni** [comment]
Sure. I'll update later today.

**Comment by anuragsoni** [comment]
The build with docs enabled also failed. I'll also add `odoc` as a doc dependency

**Comment by Drup** [comment]
I think you forgot to push.

**Comment by anuragsoni** [comment]
I did indeed. Updated the PR

**Comment by anuragsoni** [comment]
Could the documentation failures be linked to travis attempting to update gh-pages branch with an invalid token?

**Comment by Drup** [comment]
No. It tries to build the doc in dev mod, where warning are fatal. In release mod, warning are non fatal. It doesn't matter, I'll fix it later.

**Comment by Drup** [comment]
Thanks!

**Comment by anuragsoni** [comment]
ah! that makes sense!

**Pull request merged**
